### ISSUE TITLE
Guards often are missing armors

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#354]
**Describe the bug**
Guards in OA and other cities are often missing armors.

**To Reproduce**
1. Go to OA Eastern gate
2. Notice guards missing gear

**Expected behavior**
They should have armor

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/60405799/4cfe48bb-293c-411a-b9e3-35fb46a793eb)

**Character info:**

```
fail: AOEmu.Common.Entities.PlayfieldCell[0]
      Male Blade <100002> - Failed npc heartbeat!
fail: AOEmu.Common.Entities.PlayfieldCell[0]
      System.AggregateException: One or more errors occurred. (Failed to instantiate item 285155)
       ---> System.Exception: Failed to instantiate item 285155
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at AOEmu.PlayfieldEngine.Entities.Item.ItemFactory.GetItemById(Int32 id, Boolean eagerStats, Boolean eagerAcg, Boolean eagerCriteria) in /home/andrew/src/prk/engines/AOEmu.PlayfieldEngine/Entities/Item/ItemFactory.cs:line 248
         --- End of inner exception stack trace ---
         at AOEmu.PlayfieldEngine.Entities.Item.ItemFactory.GetItemById(Int32 id, Boolean eagerStats, Boolean eagerAcg, Boolean eagerCriteria) in /home/andrew/src/prk/engines/AOEmu.PlayfieldEngine/Entities/Item/ItemFactory.cs:line 254
         at AOEmu.PlayfieldEngine.Entities.Item.ItemFactory.GetItemByIds(List`1 ids, Int32 ql, Boolean eagerStats, Boolean eagerAcg, Boolean eagerCriteria) in /home/andrew/src/prk/engines/AOEmu.PlayfieldEngine/Entities/Item/ItemFactory.cs:line 350
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at AOEmu.Common.Entities.NonPlayerCharacter.CalculateModifiers(Boolean skipAppearanceUpdate) in /home/andrew/src/prk/engines/AOEmu.PlayfieldEngine/Entities/NonPlayerCharacter.cs:line 434
         at AOEmu.PlayfieldEngine.Systems.CellManagementSystem.HeartbeatNpc(KeyValuePair`2 npc, TimeSpan delta) in /home/andrew/src/prk/engines/AOEmu.PlayfieldEngine/Systems/CellManagementSystem.cs:line 335
         at AOEmu.Common.Entities.PlayfieldCell.HeartbeatCell(IPlayfieldInstance pfi, TimeSpan delta) in /home/andrew/src/prk/engines/AOEmu.PlayfieldEngine/Entities/PlayfieldCell.cs:line 441

```

**Comment by portalerprk** [comment]
After analysis this appears to just be another case of mismatched server and rdb data.

**Comment by portalerprk** [comment]
@3F1-1009  can we close this now?

**Comment by 3F1-1009** [comment]
There are still some missing, but I think the issue can be closed as we are working on it as we go.
